version: "2.1"
volumes:
  data-volume:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.100,async,nolock,soft,rw"
      device: /volume1/Content

services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - UMASK_SET=022
    volumes:
      - ./config/radarr:/config
      - ~/shares/Content/Movies:/movies
      - ~/shares/Downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - UMASK_SET=022
    volumes:
      - ./config/sonarr:/config
      - data-volume/TV:/tv
      - data-volume/Anime:/anime
      - ~/shares/Downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - AUTO_UPDATE=true
    volumes:
      - ./config/jackett:/config
      - ~/shares/Downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - ./config/sabnzbd:/config
      - ~/shares/Content/Movies:/movies
      - ~/shares/Content/TV:/tv
      - ~/shares/Content/Anime:/anime
      - ~/shares/Downloads:/downloads
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped

  nzbhydra2:
    image: ghcr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - ./config/nzbhydra2:/config
      - ~/shares/Downloads:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped

  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - UMASK_SET=022 #optional
    volumes:
      - ./config/bazarr:/config
      - ~/shares/Content/TV:/tv
      - ~/shares/Content/Movies:/movies
    ports:
      - 6767:6767
    restart: unless-stopped

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - ./config/transmission:/config
      - ~/shares/Downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

